//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('courses')
export class coursesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  courseTitle: string;

  @Column('text', { nullable: true })
  courseDescription: string;

  @Column('text', { nullable: true })
  instructorName: string;

  @Column('date', { nullable: true })
  startDate: Date;

  @Column('text', { nullable: true })
  collectionOfProblemsOrExercises: string;

  @Column('text', { nullable: true })
  answerOrSolutionToTheProblemSets: string;
}
