//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    courses: {
      name: 'Courses',
      fields: {
        courseTitle: 'Course Title',
        courseDescription: 'Course Description',
        instructorName: 'Instructor Name',
        startDate: 'Start Date',
        collectionOfProblemsOrExercises: 'Collection Of Problems Or Exercises',
        answerOrSolutionToTheProblemSets:
          'Answer Or Solution To The Problem Sets',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    courses: {
      name: 'Courses (fr)',
      fields: {
        courseTitle: 'Course Title (fr)',
        courseDescription: 'Course Description (fr)',
        instructorName: 'Instructor Name (fr)',
        startDate: 'Start Date (fr)',
        collectionOfProblemsOrExercises:
          'Collection Of Problems Or Exercises (fr)',
        answerOrSolutionToTheProblemSets:
          'Answer Or Solution To The Problem Sets (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
